apiVersion: apps/v1
kind: Deployment
  # {{ .Values.customblock.author.name}}
  # {{ .Values.customblock.author.addess | nindent 4}}
  # {{ .Values.customblock.author.addesss | default "Hi, I am not Null" | nindent 6}}
  # {{ .Values.customblock.author.addess | default "Hi, I am not Null" | upper | nindent 8 }}
  # {{ .Values.customblock.author.addess | default "Hi, I am not Null" | upper | quote | nindent 10 }}

  # {{ .Chart.Keywords}}

  # {{- if not .Values.customblock.author.name}}
  # {{"Custom Value is present" | nindent 4}}
  # {{- end}}

  #  {{- if .Values.customblock.author.name}}
  # {{"Custom Value is present" | nindent 4}}
  # {{- else}}
  # {{"Custom Value is not present" | nindent 4}}
  # {{- end}}

  # {{ - with .Values.customblock.author.name }}
  # {{ - toYaml . | nindent 4 }}
  # {{ -else }}
  # {{ "I am without with block" | nindent 4 }}
  # {{ - end }}

  # {{ $myVar := "Hello World" }}
  # {{- if eq $myVar "Hello World" }}
  # {{- $myVar | nindent 4 }}
  # {{- else }}
  # {{- $myVar | upper | nindent 4 }}
  # {{- end }}

  {{ range $key, $value := .Values.customblock.author.name }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}

author:
  {{- range $key, $value := .Values.customblock.author.name }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  

metadata:
  name: {{ include "my-first-chart.fullname" . }}
  labels:
    {{- include "my-first-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-first-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-first-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-first-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
